module.exports = {
	OlympeApi: require("./src/OlympeApi.js"),
	ApiChallenge: require("./src/routes/ApiChallenges.js"),
	ApiDiscord: require("./src/routes/ApiDiscord"),
	ApiInvitation: require("./src/routes/ApiInvitation"),
	ApiMarketPlace: require("./src/routes/ApiMarketPlace"),
	ApiMatchs: require("./src/routes/ApiMatchs"),
	ApiOrganization: require("./src/routes/ApiOrganization"),
	ApiPool: require("./src/routes/ApiPool"),
	ApiSegment: require("./src/routes/ApiSegment"),
	ApiStep: require("./src/routes/ApiStep"),
	ApiTeams: require("./src/routes/ApiTeams"),
	ApiTicket: require("./src/routes/ApiTicket"),
	ApiUsers: require("./src/routes/ApiUsers"),
};
